[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_anchor_program = "DTUAttzAbV6PAKp6Gz1mJgRcxR7FUx69ZFz6gUAJBti5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/shivankkapur/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
